# Generated by Django 3.2.8 on 2024-04-23 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0004_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
    ]
