# Generated by Django 3.2.8 on 2024-04-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0008_alter_vehicle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
