# Generated by Django 3.2.8 on 2024-04-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0009_vehicle_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='hire_price',
            field=models.DecimalField(decimal_places=2, help_text='单位：元/天', max_digits=7),
        ),
    ]
