# Generated by Django 3.2.8 on 2024-05-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0010_alter_vehicle_hire_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.CharField(choices=[('南京浦口店', '南京浦口店'), ('南京鼓楼店', '南京鼓楼店'), ('南京江宁店', '南京江宁店'), ('南京雨花店', '南京雨花店'), ('南京秦淮店', '南京秦淮店')], default='南京浦口店', max_length=100),
        ),
    ]
