# Generated by Django 3.2.8 on 2024-05-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0011_vehicle_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='location',
            new_name='store',
        ),
    ]
