# Generated by Django 3.2.8 on 2024-06-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0014_alter_client_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='hired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
